### ISSUE TITLE
model.search() returns undefined

### ISSUE THREAD

**Issue by framirezt** [Didas-git/Nekdis#19]
I am trying out this pr to implement vector similarity searching on my application. I did some basic testing to see how it works and created a user schema, however when creating the users, the createAndSave() does store the user but returns undefined. Then I tested searching the users but it returns undefined as well on all searches. It could also be that I am missing something , I attach some snippets of how I implemented it: 

```
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\  CREATING SCHEMA  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\  
// Connect to the db
await client.connect(url);

// Create the schema
const userSchema = client.schema({
  firstName: "string",
  lastName: "string",
  age: "number",
  verified: "boolean",
  location: "point",
  skills: "array",
  personalStatement: { type: "text", phonetic: "dm:es" },
  vectorEmbedding: {
    type: "vector",
    index: true,
    algorithm: "HNSW",
    dim: 128,
    distance: "COSINE",
    vecType: "FLOAT32",
    optional: true,
  },
});

// Create the interface
const User = client.model("User", userSchema);

// Create the search index
await User.createIndex();

export default User;

```
```
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\  CREATING USER  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\  

export const createUser = async (req, res) => {
  const user = await User.createAndSave(req.body);

  console.log(user);
 // undefined

  res.send({ user });
};
```

```
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\  SEARCHING USER  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\  

export const searchUser = async (req, res) => {
  const  users = await User.search().returnAll();

  console.log(users);
 // undefined and .count() returns 0

  res.send({ users });
};
```

**Comment by Didas-git** [comment]
when you call `createAndSave` it will always return undefined if it doesnt throw this is because it doesnt actually have a return value (its void/undefined).

Regarding the search result, it is pretty weird because the method used is the same as `redis-om-node`.
I took a look at the index information and it seems like RediSearch is not indexing the documents, im going to do some research/investigation on the matter and give a follow up as soon as i have and answer for the issue.

**Comment by framirezt** [comment]
Thank you Didas. Something that seemed weird as well was that when creating the documents, they do show up on the "Filter by Keyname" tab in RedisInsight, but when I select the "Search by values of keys" they dont show up.

_(the "person" index was created using redis-om, and the "user" index with Nekdis)_



- **Filter by Keyname**
<img width="615" alt="Screenshot 2023-10-01 at 7 55 45 PM" src="https://github.com/Didas-git/Nekdis/assets/90357987/19eb68b3-6f90-481d-8c13-80c364d6930b">


- **Search by values of keys**
<img width="604" alt="Screenshot 2023-10-01 at 7 56 32 PM" src="https://github.com/Didas-git/Nekdis/assets/90357987/f65009d2-a36b-4996-9079-48b18d735d64">


- **On Person index (from redis-om) it does show the values**
<img width="603" alt="Screenshot 2023-10-01 at 8 01 24 PM" src="https://github.com/Didas-git/Nekdis/assets/90357987/1f8c0566-0658-49f1-ba95-b0ff8dfec752">

**Comment by Didas-git** [comment]
After some digging it looks like the documents are not being indexed when an invalid vector is stored, so when the vector is optional and you dont pass it in Nekdis is saving an empty array which is causing this issue when you dont specify a vector.

**Comment by framirezt** [comment]
It worked! Thank you Didas. It seems the problem was the 'optional: true'. I removed it and the searching is working perfectly

**Comment by Didas-git** [comment]
> It worked! Thank you Didas. It seems the problem was the 'optional: true'. I removed it and the searching is working perfectly

If you update to the latest version you can keep the `optional` if you want.
